<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname(dirname($vendorDir)));

return array(
    'BoldMinded\\SimpleGrids\\Dependency\\Symfony\\Polyfill\\Ctype\\' => array($vendorDir . '/symfony/polyfill-ctype'),
    'BoldMinded\\SimpleGrids\\Dependency\\Symfony\\Component\\Yaml\\' => array($vendorDir . '/symfony/yaml'),
    'BoldMinded\\SimpleGrids\\Dependency\\Litzinger\\FileField\\' => array($vendorDir . '/litzinger/file-field/src'),
    'BoldMinded\\SimpleGrids\\Dependency\\Litzinger\\Basee\\' => array($vendorDir . '/litzinger/basee/src'),
    'BoldMinded\\SimpleGrids\\Dependency\\Bamarni\\Composer\\Bin\\' => array($vendorDir . '/bamarni/composer-bin-plugin/src'),
    'BoldMinded\\SimpleGrids\\' => array($baseDir . '/addons/simple_grids'),
);
